name: 🚀 Deploy update on merge to dev
on:
  push:
    branches:
      - develop

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Deploy to server via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ftp.staging.legalpediaresources.com
          username: developer@staging.legalpediaresources.com
          password: ${{ secrets.STAGINGPASSWORD }}
          port: 22
          source: "./"                # take all repo files
          target: "/home/legaxdfh/teststaging" # destination path on server
